# Fetch on-chain data from BigQuery

- Author: Yichen Luo
- Date: 2024-10-01

## Dependencies

run following commands in the terminal first

```bash
pip install --upgrade google-cloud-bigquery
```

In [3]:
import os

from google.cloud import bigquery
from pandas import json_normalize

## Google BigQuery

Google BigQuery is a serverless, highly scalable, and cost-effective multi-cloud data warehouse designed for business agility. It enables super-fast SQL queries using the processing power of Google's infrastructure. BigQuery is a powerful tool for data analysis and visualization.

### Blockchain Data on BigQuery

Google BigQuery provides a dataset of blockchain data from various blockchains, including Bitcoin, Ethereum, and Litecoin. The dataset is updated regularly and contains a wealth of information about the blockchain, such as transactions, blocks, addresses, and more.

### Accessing Blockchain Data on BigQuery Playground

- Step 1: Go to the [Google Cloud Console](https://console.cloud.google.com/).
  
<img src="./fig/console.png" width="1400">

- Step 2: Create a new project or select an existing project.

<img src="./fig/new_project.png" width="1400">

<img src="./fig/project_settings.png" width="1400">

<img src="./fig/new_project.png" width="1400">

<img src="./fig/select_project.png" width="1400">


- Step 3: Enter the BigQuery console.

<img src="./fig/bigquery.png" width="1400">

- Step 4: Select the dataset you want to query.

<img src="./fig/select_dataset.png" width="1400">

- Step 5: Open the playground to run SQL queries.

<img src="./fig/playground.png" width="1400">

- Step 6: Write and run your SQL query to fetch blockchain data.

<img src="./fig/example_query.png" width="1400">

### Accessing Blockchain Data using API

- Step 1: Enter the credentials page.

<img src="./fig/credentials.png" width="1400">

<img src="./fig/service_acct.png" width="1400">

- Step 2: Create a service account.

<img src="./fig/service_acct_id.png" width="1400">

<img src="./fig/role_assign.png" width="1400">

<img src="./fig/select_acct.png" width="1400">

<img src="./fig/create_key.png" width="1400">

- Step 3: Download the JSON key file.

<img src="./fig/create_json.png" width="1400">


- Step 4: Put the JSON key file in your project directory.

### Fetching Blockchain Data using Python

In [4]:
os.environ["GOOGLE_APPLICATION_CREDENTIALS"] = "YOUR_JSON_KEY_FILE.json"
client = bigquery.Client()

# Perform a query.
query_btc = ("""
select *,
from bigquery-public-data.crypto_bitcoin.transactions
WHERE block_timestamp_month = "2024-10-01"
LIMIT 1000
""")

query_job = client.query(query_btc)  # API request
rows = query_job.result()  # Waits for query to finish


field_names = [f.name for f in rows.schema]
# needs to be done in once, otherwise 'Iterator has already started' error
btc_tx_value = [{
    field: row[field] for field in field_names
} for row in rows]

json_normalize(btc_tx_value)

,hash,size,virtual_size,version,lock_time,block_hash,block_number,block_timestamp,block_timestamp_month,input_count,output_count,input_value,output_value,is_coinbase,fee,inputs,outputs
0,bac5d5eaaef9d4df802b3c87ce7dc11ba0368b8870a97b...,223,142,2,0,00000000000000000002f3682b2b9b13ace9a83e068120...,863778,2024-10-02 07:57:34+00:00,2024-10-01,1,2,353276881,353271201,False,5680,"[{'index': 0, 'spent_transaction_hash': '1893d...","[{'index': 0, 'script_asm': 'OP_HASH160 708650..."
1,479e3b202b8d14ade8e07d3a4a5e5219dbf19c4709ddba...,223,223,2,0,00000000000000000002f3682b2b9b13ace9a83e068120...,863778,2024-10-02 07:57:34+00:00,2024-10-01,1,2,22641165,22636121,False,5044,"[{'index': 0, 'spent_transaction_hash': 'ad6a6...","[{'index': 0, 'script_asm': 'OP_HASH160 36278a..."
2,fe1a150f24de91d4107ef15926a22c46bc443d3eccc003...,222,141,2,0,00000000000000000002f3682b2b9b13ace9a83e068120...,863778,2024-10-02 07:57:34+00:00,2024-10-01,1,2,978090,972450,False,5640,"[{'index': 0, 'spent_transaction_hash': '1415a...","[{'index': 0, 'script_asm': '0 6e9195ee11b0a73..."
3,ae3d20017edcfd99d4b181e7c4cb1844f798d0b3a32e91...,225,144,2,0,00000000000000000002f3682b2b9b13ace9a83e068120...,863778,2024-10-02 07:57:34+00:00,2024-10-01,1,2,238024501,238018741,False,5760,"[{'index': 0, 'spent_transaction_hash': '8139b...","[{'index': 0, 'script_asm': 'OP_DUP OP_HASH160..."
4,d7c9dde205d2766aac3018fb7ca8df6a48fe52a8526378...,383,192,1,863777,00000000000000000002f3682b2b9b13ace9a83e068120...,863778,2024-10-02 07:57:34+00:00,2024-10-01,1,2,57002,47352,False,9650,"[{'index': 0, 'spent_transaction_hash': 'fe127...","[{'index': 0, 'script_asm': 'OP_DUP OP_HASH160..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,d63e12b200dbb63d59436946c4afc320eaf82fa2b14260...,208,126,2,0,00000000000000000002f3682b2b9b13ace9a83e068120...,863778,2024-10-02 07:57:34+00:00,2024-10-01,1,2,8600,8380,False,220,"[{'index': 0, 'spent_transaction_hash': '0bfe1...","[{'index': 0, 'script_asm': '0 462978bc709c48b..."
996,6238512934c08c682439ea932debedbd9a70c613f8d6ab...,207,126,2,0,00000000000000000002f3682b2b9b13ace9a83e068120...,863778,2024-10-02 07:57:34+00:00,2024-10-01,1,2,24120,23900,False,220,"[{'index': 0, 'spent_transaction_hash': '62449...","[{'index': 0, 'script_asm': '0 462978bc709c48b..."
997,d9bff8474b2a118f0dab1ea26f0aa6e8389a2298c1fbda...,207,126,2,0,00000000000000000002f3682b2b9b13ace9a83e068120...,863778,2024-10-02 07:57:34+00:00,2024-10-01,1,2,23020,22800,False,220,"[{'index': 0, 'spent_transaction_hash': '0559a...","[{'index': 0, 'script_asm': '0 462978bc709c48b..."
998,ecaaa20eefee27c019043b41020ee33a50340046bd67e1...,207,126,2,0,00000000000000000002f3682b2b9b13ace9a83e068120...,863778,2024-10-02 07:57:34+00:00,2024-10-01,1,2,22360,22140,False,220,"[{'index': 0, 'spent_transaction_hash': 'fb87f...","[{'index': 0, 'script_asm': '0 462978bc709c48b..."
999,76aef65ee3413362f9b8c0ba330a1657b8638c1b139657...,208,126,2,0,00000000000000000002f3682b2b9b13ace9a83e068120...,863778,2024-10-02 07:57:34+00:00,2024-10-01,1,2,23020,22800,False,220,"[{'index': 0, 'spent_transaction_hash': 'a5793...","[{'index': 0, 'script_asm': '0 462978bc709c48b..."